version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12334543321
      - POSTGRES_USER=postgres
      - POSTGRES_DB=lab 4 web
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:5000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=12334543321
      - DB_NAME=lab 4 web
    depends_on:
      - db
    volumes:
      - .:/usr/src/app